image: $CI_REGISTRY/$DOCKER_IMAGE_NAMESPACE/gradle-46:latest

stages:
  - build
  - test
  - upload

# Disable the Gradle daemon to isolating each build.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle

before_script:
  - /opt/altapay/create-gradle-properties.sh ${GRADLE_USERNAME} ${GRADLE_PASSWORD}

build:
  stage: build
  artifacts:
    paths:
      - build/
  script:
    - gradle --build-cache assemble

test-unit:
  stage: test
  script:
    - gradle test
  artifacts:
    reports:
      junit: ["build/test-results/test/TEST-*.xml"]

test-functional:
  stage: test
  script:
    - gradle functional
  artifacts:
    reports:
      junit: ["build/test-results/functional/TEST-*.xml"]

test-integration:
  stage: test
  script:
    - gradle integration
  artifacts:
    reports:
      junit: ["build/test-results/integration/TEST-*.xml"]

upload:
  image: $CI_REGISTRY/$DOCKER_IMAGE_NAMESPACE/rsync-buildmaster:latest
  stage: upload
  script:
    - /opt/altapay/upload.sh build/distributions/*.tgz javasdk
  only:
    - master
