name: Java SDK Build and Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Create gradle.properties file
        run: |
          echo signing.keyId=${{secrets.GPG_KEY_ID}} > gradle.properties
          echo signing.password=${{secrets.GPG_KEY_PASSPHRASE}} >> gradle.properties
          echo signing.secretKeyRingFile=secring.gpg >> gradle.properties
          echo usr=${{ secrets.OSSRH_USERNAME }} >> gradle.properties
          echo pwd=${{ secrets.OSSRH_TOKEN }} >> gradle.properties

      - name: Run Tests
        run: ./gradlew test
