name: Java SDK Build and Run Tests

on:
  push:
    branches: [ java-opensource ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Ant
        run: ant DistZip
