name: Java SDK Build and Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Ant
        run: ant DistZip

      - name: Generate Class files
        run: javac -classpath .:output/*:devlib/* test/unit/com/pensio/api/*.java

      - name: Run Tests
        run: java -classpath .:${GITHUB_WORKSPACE}/output/*:${GITHUB_WORKSPACE}/devlib/* org.junit.runner.JUnitCore com.pensio.api.SuiteAltaPayTest
        working-directory: test/unit
